### ISSUE TITLE
Styling GeoJSON

### ISSUE THREAD

**Issue by KamilDwo** [tcoupin/leaflet-paintpolygon#3]
How to change style of GeoJSON element using Leaflet.

for example set this style: 
`let style = {
    radius: 8,
    fillColor: "#ff7800",
    color: "#000",
    weight: 1,
    opacity: 1,
    fillOpacity: 0.8
};`

**Comment by tcoupin** [comment]
Oups, I forget this options...

**Comment by KamilDwo** [comment]
#4

**Comment by tcoupin** [comment]
Thanks for your PR!
I added an example: https://github.com/tcoupin/leaflet-paintpolygon/blob/master/examples/4_style.html
